增加beats提取文件和alignment文件
SJTMusicTeam/SVS_system pull request #1
Opened 2020-02-12 03:11 UTC by yiwangaosimian

两个文件的输入输出都需要之后根据文件格式进行修改，大致框架已经写好

2020-02-12 03:30 UTC, ftshijt requested changes

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +    Max = -math.log(1e-300,2)
这个是怎么选取的呢

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +            if j >= 2:
也就是现在是考虑到跳帧的情况对吧

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +    file = open('/Users/linhailan1/Desktop/林海斓/phone.post','r')
这里需要封装一下，file可以作为参数传进来，因为之后批量处理需要大量调用（一般decode出来的应该是按job分的，我记得默认是32）

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +    file = open('/Users/linhailan1/Desktop/林海斓/phone.post','r')
从开源的角度也最好封装下

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +    post = file.readlines()
readlines有局限的，一般不要采用这种方式（它有可能读不完），不过我们这个问题上应该不会出现内存不够的情况，这里暂时不用改了

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +    file = open('/Users/linhailan1/Desktop/林海斓/phones.txt','r')
这里的file也用参数传进去

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +        if line[0] == '#':  break
我的感觉是尽量在这里就把不同声调的同一音素合起来，最后同时生成一个新的音素表（原来的那个我们之后再训练没法用

2020-02-12 03:30 UTC, ftshijt commented on preprocessing/pitch_beat_extraction.py
> +只有一首歌的beats提取，pitch提取尚未完成
用argparse封装一下

2020-02-12 03:32 UTC, ftshijt commented
关于计算post的算法，你需要也写一个shell脚本（就按照先提特征（这个和run.sh一致），再计算post（之前电话联系的那一套东西），自动生成之后，调用你alignment的脚本进行align，align的结果数据最后以统一格式存储

2020-02-12 03:33 UTC, ftshijt commented
还有个小小问题是，注释最好写英文的（这样之后开源出去，不会受限制

2020-02-12 07:37 UTC, yiwangaosimian commented on preprocessing/alignment/alignment.py
> +            if j >= 2:
是考虑模版中音素的跳跃，可以参照如下的图。
然后这个是边界情况的判断，担心数组越界，不知道需不需要，不需要的话我可以改一下。 
![The next input frame aligns to the same template frame as the previous](https://user-images.githubusercontent.com/39286767/74312924-9d2eea80-4dad-11ea-9086-4923e6ce97d4.png)

2020-02-12 07:45 UTC, yiwangaosimian commented on preprocessing/alignment/alignment.py
> +    Max = -math.log(1e-300,2)
在text_to_matrix()函数里，我将最小概率设置为1e-300，为了避免对0取对数导致错误，因此涌过取对数和负数后的最大值就是Max，我将其他不存在概率的音素统一赋值为最大值（即概率的最小值），虽然这样会导致概率和大于1，但这不影响结果。

2020-02-12 07:46 UTC, yiwangaosimian commented on preprocessing/alignment/alignment.py
> +    post = file.readlines()
OK！

2020-02-12 07:52 UTC, yiwangaosimian commented on preprocessing/alignment/alignment.py
> +        if line[0] == '#':  break
因为目前我有的文件就是有声调的音素，所以我在109行，将所有音素的数字都去掉了，也就是将不同声调的音素全部统一转化成没有声调（即数字）的音素。如果之后有新的音素编号对应表的话就可以更加省事了！

2020-02-12 09:02 UTC, yiwangaosimian commented on preprocessing/pitch_beat_extraction.py
> +只有一首歌的beats提取，pitch提取尚未完成
已经封装完成了，看看现在可不可以？

2020-02-12 13:24 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +            if j >= 2:
ok

2020-02-12 13:26 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +        if line[0] == '#':  break
是的，你直接生成一个phone对应表就好

2020-02-12 15:07 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +        template = ['a','b','c']        #此处应换成读模版（标注）文件并解析
这里之后应该会替换成利用text做模板，这里可能也需要做一下输入的封装，建议加参数到parser里面去

2020-02-12 15:07 UTC, ftshijt commented on preprocessing/alignment/alignment.py
> +    file = open(args.phone_map_path,'r')
用with吧，现在里面时不时file.close()有点怪怪的

2020-02-16 14:36 UTC, ftshijt commented on preprocessing/pitch_beat_extraction.py
> +parser = argparse.ArgumentParser()
这个文件改一下名字

2020-02-20 03:34 UTC, merged